## DEPLOYMENTS
# REDIS
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spider
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        ports:
        - containerPort: 6379
        resources: 
          requests:
            cpu: 150m
            memory: 2Gi
          limits:
            cpu: 500m
            memory: 4Gi
        volumeMounts:
        - mountPath: /data
          name: redis-claim0
      restartPolicy: Always
      volumes:
      - name: redis-claim0
        emptyDir: {}
        #PROD#persistentVolumeClaim:
        #PROD#  claimName: redis-cephfs-claim
status: {}