# FLOWER
apiVersion: v1
kind: Service
metadata:
  namespace: spider
  labels:
    io.kompose.service: spider-flower
  name: spider-flower
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    app: spider-flower
  type: NodePort
status:
  loadBalancer: {}