# REDIS-CHECKPOINT
apiVersion: v1
kind: Service
metadata:
  namespace: spider
  labels:
    io.kompose.service: redis-checkpoint
  name: redis-checkpoint
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: redis-checkpoint
status:
  loadBalancer: {}